// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqu1F77x2ej2YV49R4XBbuf8OqVvxhK9s',
    appId: '1:860785271450:web:140563edcc5abd54e9b523',
    messagingSenderId: '860785271450',
    projectId: 'chat-test-app-77bc0',
    authDomain: 'chat-test-app-77bc0.firebaseapp.com',
    storageBucket: 'chat-test-app-77bc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMFLy9hcfDC8W3fiVa5UFEZkZ1yZcu08',
    appId: '1:860785271450:android:f5e38db2ab03b7a5e9b523',
    messagingSenderId: '860785271450',
    projectId: 'chat-test-app-77bc0',
    storageBucket: 'chat-test-app-77bc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9x5Ygc9VNvUofcqmKjCGMxB2yn1O66V8',
    appId: '1:860785271450:ios:1798f09d66eedbc1e9b523',
    messagingSenderId: '860785271450',
    projectId: 'chat-test-app-77bc0',
    storageBucket: 'chat-test-app-77bc0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9x5Ygc9VNvUofcqmKjCGMxB2yn1O66V8',
    appId: '1:860785271450:ios:9dc46258b79563e3e9b523',
    messagingSenderId: '860785271450',
    projectId: 'chat-test-app-77bc0',
    storageBucket: 'chat-test-app-77bc0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
